{
 "title": "学习机PSM框架监控",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "psm",
    "label": "psm",
    "query": "{\"find\":\"terms\", \"field\":\"x_psm\", \"size\":1000}"
   },
   {
    "name": "handler",
    "label": "handler",
    "query": "{\"find\":\"terms\", \"field\":\"x_handler_path\", \"size\":1000, \"query\":\"x_psm:$psm\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "PSM流量监控",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "rpc qps",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "x_tag: \"arch_grpc_qps\" AND x_psm: $psm AND x_handler_path: $handler",
     "timeField": "@timestamp"
    },
    {
     "alias": "gin qps",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "x_tag: \"arch_ginx_qps\" AND x_psm: $psm AND x_handler_path: $handler",
     "timeField": "@timestamp"
    },
    {
     "alias": "keepalive close",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "x_tag: \"arch_grpc_closed\" AND x_psm: $psm",
     "timeField": "@timestamp"
    },
    {
     "alias": "rpc熔断",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "x_tag: \"arch_grpc_circuit\" AND x_psm: $psm",
     "timeField": "@timestamp"
    },
    {
     "alias": "gin 限流",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "x_tag: \"arch_ginx_limit\" AND x_psm: $psm",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "学习机终端总量",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "snCount{}" }
   ]
  },
  {
   "title": "Pod 总量",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(podCount{psm=~\"$psm\"})",
     "legendFormat": "$psm"
    }
   ]
  },
  {
   "title": "Process硬件使用率 avg",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(cpuPercent{psm=~\"$psm\"})",
     "legendFormat": "cpu"
    },
    {
     "expr": "avg(memPercent{psm=~\"$psm\"})",
     "legendFormat": "内存"
    }
   ]
  },
  {
   "title": "redis命中率 avg",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(redisHitPercent{psm=~\"$psm\"})",
     "legendFormat": "$psm"
    }
   ]
  },
  {
   "title": "Mysql avg QPS",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(mysqlAvgQps{psm=~\"$psm\"})",
     "legendFormat": "$psm"
    }
   ]
  },
  {
   "title": "协程数 avg",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(goroutineCount{psm=~\"$psm\"})",
     "legendFormat": "$psm"
    }
   ]
  },
  {
   "title": "Kafka err EPS",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(kafkaErrAvgEps{psm=~\"$psm\"})",
     "legendFormat": "$psm"
    }
   ]
  },
  {
   "title": "流量分布",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "alias": "psm",
     "bucketAggs": [
      {
       "field": "x_psm",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "5", "type": "count" }
     ],
     "query": "x_psm:$psm AND (x_tag:arch_grpc_qps OR x_tag:arch_ginx_qps) AND x_handler_path: $handler",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "handler 方法调用分布  top 10",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "x_handler_path",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "x_date", "id": "5", "settings": { "interval": "7d", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "4",
       "type": "count"
      }
     ],
     "query": "x_psm:$psm AND -x_handler_path :\"\" AND x_handler_path: $handler",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "时延",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "x_date", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "x_handler_period", "id": "1", "type": "max" }
     ],
     "query": "x_psm: $psm AND x_handler_period:>=0 AND x_handler_path: $handler",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "时延 P999 分布",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "x_handler_path", "id": "2", "settings": { "order": "desc", "orderBy": "1[99.9]", "size": "0" }, "type": "terms" }
     ],
     "metrics": [
      {
       "field": "x_handler_period",
       "id": "1",
       "settings": {
        "percents": [
         "95",
         "99.9"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "x_psm: $psm AND x_handler_period:>=0 AND x_handler_path: $handler",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "系统错误/业务ERR",
   "type": "timeseries",
   "description": "错误信息的分布",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "框架埋点错误",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "x_tag: \"arch_error\" AND x_psm: $psm",
     "timeField": "@timestamp"
    },
    {
     "alias": "框架Panic捕获",
     "bucketAggs": [
      { "field": "x_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "x_tag: \"arch_fatal\" AND x_psm: $psm",
     "timeField": "@timestamp"
    },
    {
     "alias": "业务错误日志",
     "bucketAggs": [
      { "field": "x_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "x_level: \"ERROR\" AND x_psm: $psm",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "业务logger.Error",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 9, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "x_psm",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "x_date", "id": "5", "settings": { "interval": "7d", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "4",
       "type": "count"
      }
     ],
     "query": "x_level: \"ERROR\" AND x_psm:$psm",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "panic错误分布",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "x_psm",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "x_date", "id": "5", "settings": { "interval": "7d", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "4",
       "type": "count"
      }
     ],
     "query": "x_tag: \"arch_fatal\" AND x_psm: $psm",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "错误原日志",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "(x_tag: arch_fatal OR x_tag: arch_error OR x_level: ERROR) AND x_psm:$psm",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "服务发现",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "服务列表空",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "x_tag: \"arch_host_empty\" AND x_psm: $psm",
     "timeField": "@timestamp"
    },
    {
     "alias": "服务列表污染",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "x_tag: \"arch_sf_contaminate\" AND x_psm: $psm",
     "timeField": "@timestamp"
    },
    {
     "alias": "服务列表校验",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "x_tag: \"arch_sf_diff\" AND x_psm: $psm",
     "timeField": "@timestamp"
    },
    {
     "alias": "服务过期",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "x_tag: \"arch_etcd_lease_expire\" AND x_psm: $psm",
     "timeField": "@timestamp"
    },
    {
     "alias": "服务注册",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "x_tag: \"arch_etcd_put\" AND x_psm: $psm",
     "timeField": "@timestamp"
    },
    {
     "alias": "服务平滑下线",
     "bucketAggs": [
      { "field": "x_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "x_tag: \"arch_etcd_del\" AND x_psm: $psm",
     "timeField": "@timestamp"
    },
    {
     "alias": "服务查询",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "x_tag: \"arch_etcd_get\" AND x_psm: $psm",
     "timeField": "@timestamp"
    },
    {
     "alias": "配置中心下发",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "x_tag: \"arch_tcm_update\" AND x_psm: $psm",
     "timeField": "@timestamp"
    },
    {
     "alias": "监听管道-注册",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "x_tag: \"arch_etcd_watch_put\" AND x_psm: $psm",
     "timeField": "@timestamp"
    },
    {
     "alias": "监听管道-销毁",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "x_tag: \"arch_etcd_watch_del\" AND x_psm: $psm",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}