# vim /usr/local/prometheus/prometheus.yml
global:
  scrape_interval:     20s   # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 20s    # # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: "node_exporter"
    http_sd_configs:
      - url: http://app.xxx.com/monitor/hosts
      - url: http://xxx.com/hosts  # k8s not support cause idc could not ping docker ip.